### ISSUE TITLE
Pi Wall

### ISSUE THREAD

**Issue by chuco61** [vigsterkr/pi-wall#1]
Is this a streamlined version of PiWall for Rpi? I am using RPi 3's.

**Comment by vigsterkr** [comment]
@chuco61 i've only tested this with RPi v1 if you are seeing any problems could you please paste it here and i'll try to address them. thnx

**Comment by SKYMIGHT** [comment]
Hi vigsterkr:

I have a problem about Pi wall.
Would you kindly give me some help?

When I execute pi-wall(./pi-wall.py),I got some error message on my RPi3
Here are my environment:
Image:2016-03-18-raspbian-jessie.img
Device:Rpi3
Python verion: 2.7 & 3.4

Here is my error message:
Traceback (most recent call last):
  File "./pi-wall.py", line 25, in <module>
    int(config['master_port']))
  File "/home/pi/temp/pi-wall/src/player.py", line 105, in **init**
    super(MasterPlayer, self).**init**(filepath)
  File "/home/pi/temp/pi-wall/src/player.py", line 37, in **init**
    video_sink.set_property('sync', True)
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by vigsterkr** [comment]
@chuco61 @SKYMIGHT sorry for the long delay... this should fix the problem
